#!/usr/bin/env python3

from pymongo import MongoClient
database = MongoClient('localhost', 27017).twitter

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-database')
args = parser.parse_args()

def contribute(mergeBase,collection):
    collection.drop()
    # aggregate=collection.find({})
    # for document in aggregate:
    #     mergeBase.insert_one(document)

def main():
    collections=database.collection_names()
    for collection in collections:contribute(database[args.database],database[collection])

main()
